/**
 * sms-client
 * API for sms-send functions
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SmsSendRequest.h
 *
 * The structure to describe a request to send a text message.
 */

#ifndef COM_NVT_API_CLIENT_MODEL_SmsSendRequest_H_
#define COM_NVT_API_CLIENT_MODEL_SmsSendRequest_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace nvt {
namespace api {
namespace client {
namespace model {


/// <summary>
/// The structure to describe a request to send a text message.
/// </summary>
class  SmsSendRequest
    : public ModelBase
{
public:
    SmsSendRequest();
    virtual ~SmsSendRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SmsSendRequest members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSenderName() const;
    bool senderNameIsSet() const;
    void unsetSenderName();

    void setSenderName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getBody() const;
    bool bodyIsSet() const;
    void unsetBody();

    void setBody(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getPhone() const;
    bool phoneIsSet() const;
    void unsetPhone();

    void setPhone(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSource() const;
    bool sourceIsSet() const;
    void unsetSource();

    void setSource(const utility::string_t& value);


protected:
    utility::string_t m_SenderName;
    bool m_SenderNameIsSet;
    utility::string_t m_Body;
    bool m_BodyIsSet;
    utility::string_t m_Phone;
    bool m_PhoneIsSet;
    utility::string_t m_Source;
    bool m_SourceIsSet;
};


}
}
}
}
}

#endif /* COM_NVT_API_CLIENT_MODEL_SmsSendRequest_H_ */
