/**
 * sms-client
 * API for sms-send functions
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * IHttpBody.h
 *
 * This is the interface for contents that can be sent to a remote HTTP server.
 */

#ifndef COM_NVT_API_CLIENT_MODEL_IHttpBody_H_
#define COM_NVT_API_CLIENT_MODEL_IHttpBody_H_


#include <iostream>

namespace com {
namespace nvt {
namespace api {
namespace client {
namespace model {

class  IHttpBody
{
public:
    virtual ~IHttpBody() { }

    virtual void writeTo( std::ostream& stream ) = 0;
};

}
}
}
}
}

#endif /* COM_NVT_API_CLIENT_MODEL_IHttpBody_H_ */
