/**
 * sms-client
 * API for sms-send functions
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DefaultApi.h
 *
 * 
 */

#ifndef COM_NVT_API_CLIENT_API_DefaultApi_H_
#define COM_NVT_API_CLIENT_API_DefaultApi_H_


#include "../ApiClient.h"

#include "SmsSendRequest.h"
#include "SmsSendResponse.h"


#include <boost/optional.hpp>

namespace com {
namespace nvt {
namespace api {
namespace client {
namespace api {

using namespace com::nvt::api::client::model;



class  DefaultApi 
{
public:

    explicit DefaultApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~DefaultApi();

    /// <summary>
    /// Send a text message request.
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="smsSendRequest"></param>
    pplx::task<std::shared_ptr<SmsSendResponse>> smsSend(
        std::shared_ptr<SmsSendRequest> smsSendRequest
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}
}

#endif /* COM_NVT_API_CLIENT_API_DefaultApi_H_ */

